### ISSUE TITLE
決済注文がエラーになる

### ISSUE THREAD

**Issue by RikitoNoto** [RikitoNoto/gmo-fx-py#90]
```shell
Traceback (most recent call last):
  File "/home/venv/lib/python3.11/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutin>
    retval = await job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/src/discord_notification_system.py", line 225, in run
    self.close_trades(strategy.close_trades)
  File "/home/src/discord_notification_system.py", line 267, in close_trades
    order(
  File "/home/venv/lib/python3.11/site-packages/gmo_fx/api/close_order.py", line 174, in __call__
    return super().__call__(
           ^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/gmo_fx/api/api_base.py", line 46, in __call__
    return self._response_parser(response_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/gmo_fx/api/close_order.py", line 61, in __init__
    super().__init__(response)
  File "/home/venv/lib/python3.11/site-packages/gmo_fx/api/response.py", line 17, in __init__
    raise ApiError(err_code, message=message)
gmo_fx.errors.ApiError: <exception str() failed>
```

**Comment by RikitoNoto** [comment]
呼び出し側のSide指定が間違っていたことが原因だったためクローズ
